In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:/Users/DELL/Downloads/Mall_Customers.csv')

In [3]:
df.head()

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [5]:
df['Genre'] = df['Genre'].map({'Male':0, 'Female':1})
df

CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1      0   19                  15                      39
1             2      0   21                  15                      81
2             3      1   20                  16                       6
3             4      1   23                  16                      77
4             5      1   31                  17                      40
..          ...    ...  ...                 ...                     ...
195         196      1   35                 120                      79
196         197      1   45                 126                      28
197         198      0   32                 126                      74
198         199      0   32                 137                      18
199         200      0   30                 137                      83

[200 rows x 5 columns]

In [6]:
X = df.iloc[:, :-1].values
X

array([[  1,   0,  19,  15],
       [  2,   0,  21,  15],
       [  3,   1,  20,  16],
       [  4,   1,  23,  16],
       [  5,   1,  31,  17],
       [  6,   1,  22,  17],
       [  7,   1,  35,  18],
       [  8,   1,  23,  18],
       [  9,   0,  64,  19],
       [ 10,   1,  30,  19],
       [ 11,   0,  67,  19],
       [ 12,   1,  35,  19],
       [ 13,   1,  58,  20],
       [ 14,   1,  24,  20],
       [ 15,   0,  37,  20],
       [ 16,   0,  22,  20],
       [ 17,   1,  35,  21],
       [ 18,   0,  20,  21],
       [ 19,   0,  52,  23],
       [ 20,   1,  35,  23],
       [ 21,   0,  35,  24],
       [ 22,   0,  25,  24],
       [ 23,   1,  46,  25],
       [ 24,   0,  31,  25],
       [ 25,   1,  54,  28],
       [ 26,   0,  29,  28],
       [ 27,   1,  45,  28],
       [ 28,   0,  35,  28],
       [ 29,   1,  40,  29],
       [ 30,   1,  23,  29],
       [ 31,   0,  60,  30],
       [ 32,   1,  21,  30],
       [ 33,   0,  53,  33],
       [ 34,   0,  18,  33],
       [ 35,  

In [7]:
Y = Y = df.iloc[:, -1].values
Y

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 10)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()


In [11]:
dtc.fit(X_train, Y_train) 
dtc

DecisionTreeClassifier()

In [12]:
Y_pred = dtc.predict(X_test)    
Y_pred

array([56, 77, 61, 74, 51,  5, 12, 60, 42, 77, 49,  3, 55, 89, 34, 50, 52,
       42, 42, 83, 36, 11, 59, 60, 43, 58, 35, 39, 42, 92, 78, 73, 42, 46,
       73, 15, 75, 93, 42, 24], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:
test_score = accuracy_score(Y_test, Y_pred)
test_score

0.0

In [15]:
confusion_matrix(Y_test, Y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
y_pred_train = dtc.predict(X_train)
y_pred_train

array([23, 94, 32, 10, 51, 49, 55, 83, 50, 43, 14, 61, 48, 93, 73, 56, 86,
       55, 55, 42, 57, 52, 52, 95, 91, 59, 75, 48, 48, 50, 56, 26, 28, 83,
       49, 20, 44, 20, 59, 92, 51, 55,  4, 13, 42, 82, 60, 42, 66, 16, 60,
       13, 41, 57, 39, 87, 77, 73, 74, 17, 73, 85, 24, 68, 65, 34, 50, 90,
       69, 36, 75, 75, 42, 35, 69, 87, 27, 15, 42, 99,  5, 50, 46, 36,  6,
       11, 90, 89, 22, 56, 14, 43, 52,  5, 12, 97, 40, 71, 28, 47, 15, 31,
       88, 75, 32, 42, 43,  8, 74, 73, 47, 15, 42, 88, 17, 92, 40, 29, 61,
       17, 46, 73, 59,  5, 46,  1,  4, 58, 49, 93, 35, 76, 77, 48, 86, 88,
       92, 52, 58, 46, 60, 45, 72, 41, 35, 50, 26, 35, 39, 56,  3, 79, 78,
        1, 91, 46, 51, 79, 77, 72], dtype=int64)

In [17]:
train_score = accuracy_score(Y_train, y_pred_train)
train_score

1.0

In [33]:
parameter_grid = {'max_depth':[1,3,2,6],'min_samples_leaf':[5,7,1,3],'criterion':['gini','entropy']}

parameter_grid

{'max_depth': [1, 3, 2, 6],
 'min_samples_leaf': [5, 7, 1, 3],
 'criterion': ['gini', 'entropy']}

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
dtc = DecisionTreeClassifier() 

In [22]:
grid = GridSearchCV(estimator=dtc, param_grid=parameter_grid, cv=4, n_jobs=-1, verbose=1, scoring='accuracy')

In [23]:
grid.fit(X_train, Y_train)

Fitting 4 folds for each of 32 candidates, totalling 128 fits


GridSearchCV(cv=4, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 7, 8, 9],
                         'min_samples_leaf': [4, 8, 10, 12]},
             scoring='accuracy', verbose=1)

In [24]:
grid.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=7, min_samples_leaf=12)

In [25]:
dtc_best = grid.best_estimator_

In [26]:

y_pred = dtc_best.predict(X_test)
y_pred

array([51, 73,  4, 74, 42,  4, 88, 51, 42, 73, 46,  4, 51, 88, 88, 43, 46,
       42, 42, 74, 15, 15, 51, 42, 46, 42, 15, 73, 42, 75, 74, 73, 42, 46,
       73, 15, 15, 74,  4, 15], dtype=int64)

In [27]:
dtc_best_score = accuracy_score(Y_train, y_pred_train)
dtc_best_score

1.0

In [36]:
dtc_score = accuracy_score(Y_test, y_pred)
dtc_score

0.0