In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
churn = pd.read_csv('C:/Users/DELL/Downloads/churn_data.csv')

In [3]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   tenure            7043 non-null   int64  
 2   PhoneService      7043 non-null   object 
 3   Contract          7043 non-null   object 
 4   PaperlessBilling  7043 non-null   object 
 5   PaymentMethod     7043 non-null   object 
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object 
 8   Churn             7043 non-null   object 
dtypes: float64(1), int64(1), object(7)
memory usage: 495.3+ KB


In [4]:
churn.head()

customerID  tenure PhoneService        Contract PaperlessBilling  \
0  7590-VHVEG       1           No  Month-to-month              Yes   
1  5575-GNVDE      34          Yes        One year               No   
2  3668-QPYBK       2          Yes  Month-to-month              Yes   
3  7795-CFOCW      45           No        One year               No   
4  9237-HQITU       2          Yes  Month-to-month              Yes   

               PaymentMethod  MonthlyCharges TotalCharges Churn  
0           Electronic check           29.85        29.85    No  
1               Mailed check           56.95       1889.5    No  
2               Mailed check           53.85       108.15   Yes  
3  Bank transfer (automatic)           42.30      1840.75    No  
4           Electronic check           70.70       151.65   Yes

In [5]:
churn['PhoneService'] = churn['PhoneService'].map({'Yes':0, 'No':1})
churn['PaperlessBilling'] = churn['PaperlessBilling'].map({'Yes':0, 'No':1})
churn['Churn'] = churn['Churn'].map({'Yes':0, 'No':1})

In [6]:
churn

customerID  tenure  PhoneService        Contract  PaperlessBilling  \
0     7590-VHVEG       1             1  Month-to-month                 0   
1     5575-GNVDE      34             0        One year                 1   
2     3668-QPYBK       2             0  Month-to-month                 0   
3     7795-CFOCW      45             1        One year                 1   
4     9237-HQITU       2             0  Month-to-month                 0   
...          ...     ...           ...             ...               ...   
7038  6840-RESVB      24             0        One year                 0   
7039  2234-XADUH      72             0        One year                 0   
7040  4801-JZAZL      11             1  Month-to-month                 0   
7041  8361-LTMKD       4             0  Month-to-month                 0   
7042  3186-AJIEK      66             0        Two year                 0   

                  PaymentMethod  MonthlyCharges TotalCharges  Churn  
0              Electronic check           29.85        29.85      1  
1                  Mailed check           56.95       1889.5      1  
2                  Mailed check           53.85       108.15      0  
3     Bank transfer (automatic)           42.30      1840.75      1  
4              Electronic check           70.70       151.65      0  
...                         ...             ...          ...    ...  
7038               Mailed check           84.80       1990.5      1  
7039    Credit card (automatic)          103.20       7362.9      1  
7040           Electronic check           29.60       346.45      1  
7041               Mailed check           74.40        306.6      0  
7042  Bank transfer (automatic)          105.65       6844.5      1  

[7043 rows x 9 columns]

In [7]:
churn.drop(['customerID'],axis=1)

tenure  PhoneService        Contract  PaperlessBilling  \
0          1             1  Month-to-month                 0   
1         34             0        One year                 1   
2          2             0  Month-to-month                 0   
3         45             1        One year                 1   
4          2             0  Month-to-month                 0   
...      ...           ...             ...               ...   
7038      24             0        One year                 0   
7039      72             0        One year                 0   
7040      11             1  Month-to-month                 0   
7041       4             0  Month-to-month                 0   
7042      66             0        Two year                 0   

                  PaymentMethod  MonthlyCharges TotalCharges  Churn  
0              Electronic check           29.85        29.85      1  
1                  Mailed check           56.95       1889.5      1  
2                  Mailed check           53.85       108.15      0  
3     Bank transfer (automatic)           42.30      1840.75      1  
4              Electronic check           70.70       151.65      0  
...                         ...             ...          ...    ...  
7038               Mailed check           84.80       1990.5      1  
7039    Credit card (automatic)          103.20       7362.9      1  
7040           Electronic check           29.60       346.45      1  
7041               Mailed check           74.40        306.6      0  
7042  Bank transfer (automatic)          105.65       6844.5      1  

[7043 rows x 8 columns]

In [8]:
X = churn.iloc[:, [1,6]].values
X

array([[  1.  ,  29.85],
       [ 34.  ,  56.95],
       [  2.  ,  53.85],
       ...,
       [ 11.  ,  29.6 ],
       [  4.  ,  74.4 ],
       [ 66.  , 105.65]])

In [9]:
Y = churn.iloc[:, -1].values
Y

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 10)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression
Classifier = LogisticRegression()
Classifier.fit(X_train, Y_train)

LogisticRegression()

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = Classifier.predict(X_test)

In [14]:
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[146 197]
 [106 960]]


In [15]:
TN = cm[0][0]     
TP = cm[1][1]     
FN = cm[1][0]    
FP = cm[0][1]    


In [16]:
accuracy_score(Y_test, y_pred)

0.7849538679914834

In [17]:
recall = TP/(TP+FN)
print(recall)

0.900562851782364


In [18]:
precision = TP/(TP+FP)
print(precision)

0.8297320656871219
