In [1]:
import numpy as np

In [3]:
arr = np.array(32)
arr

array(32)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr 

array(32)

In [7]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
arr.ndim

1

In [10]:
arr = np.array([[1,2,3],[6,7,8],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [10, 11, 12]])

In [11]:
arr.shape

(3, 3)

In [12]:
arr.ndim

2

In [13]:
a = np.array(56)
b = np.array([6,7,8,9,10])
c = np.array([[4,5,6],[1,2,3]])
d = np.array([[[2,3,4],[6,7,8]],[[5,6,7],[10,11,12]],[[22,43,23],[45,65,32]]])
d

array([[[ 2,  3,  4],
        [ 6,  7,  8]],

       [[ 5,  6,  7],
        [10, 11, 12]],

       [[22, 43, 23],
        [45, 65, 32]]])

In [14]:
c

array([[4, 5, 6],
       [1, 2, 3]])

In [15]:
a

array(56)

In [16]:
b

array([ 6,  7,  8,  9, 10])