In [1]:
import numpy as np

In [2]:
a = np.array(43)
a

array(43)

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[[1,2,3],[4,5,6]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]])

In [5]:
b.shape

(2, 3)

In [6]:
c.shape

(3, 2, 3)

In [7]:
c.ndim

3

In [8]:
##function description

A = np.random.randint(0,high=10,size=(2,5),dtype=int)
A

array([[5, 6, 8, 1, 5],
       [7, 5, 3, 2, 1]])

In [9]:
A.shape

(2, 5)

In [10]:
##Average of the value in each column

B = ave_cols = np.average(A,axis=0)
B

array([6. , 5.5, 5.5, 1.5, 3. ])

In [11]:
##Create a rank ndarray that contains a random permutation of the row indices

row_indices = np.random.permutation(np.arange(10,50))
row_indices

array([16, 37, 44, 39, 25, 43, 26, 13, 36, 11, 32, 19, 21, 30, 33, 46, 47,
       48, 38, 17, 49, 28, 15, 10, 22, 41, 23, 34, 20, 45, 24, 31, 40, 35,
       27, 18, 14, 29, 42, 12])

In [12]:
row_indices.shape

(40,)

In [13]:
train = row_indices[:15]
test = row_indices[15:25]
val = row_indices[25:]


In [14]:
train

array([16, 37, 44, 39, 25, 43, 26, 13, 36, 11, 32, 19, 21, 30, 33])

In [15]:
test

array([46, 47, 48, 38, 17, 49, 28, 15, 10, 22])

In [16]:
val

array([41, 23, 34, 20, 45, 24, 31, 40, 35, 27, 18, 14, 29, 42, 12])

In [17]:
import pandas as pd

In [34]:
data = np.array(['A','B','H','I','T','A'])

In [35]:
Abhi = pd.Series(data)
print(Abhi)

0    A
1    B
2    H
3    I
4    T
5    A
dtype: object


In [36]:
print(Abhi[4])

T


In [37]:
print(Abhi.iloc[2])

H


In [38]:
print(Abhi.loc[0])

A


In [39]:
Parth = np.array(['P','A','R','T','H'])

In [43]:
Abhi = pd.Series(Parth,index=['M','E','E','R','A'])
print(Abhi)

M    P
E    A
E    R
R    T
A    H
dtype: object


In [45]:
list1 = ['w','o','r','l','d']
ser = pd.Series(list1)
print(ser)

0    w
1    o
2    r
3    l
4    d
dtype: object


In [46]:
dict = {'A':10,'B':20,'C':30}
ser = pd.Series(dict)
print(ser)

A    10
B    20
C    30
dtype: int64


In [47]:
dict = {'A':[10,20],'B':[20,30],'C':[30,40]}
ser = pd.Series(dict)
print(ser)

A    [10, 20]
B    [20, 30]
C    [30, 40]
dtype: object


In [48]:
ser = pd.Series(10,index=[0,1,2,3,4,5,6])
print(ser)

0    10
1    10
2    10
3    10
4    10
5    10
6    10
dtype: int64


In [52]:
a = [X for X in range(20,30)]
Abhi = pd.DataFrame(a)
print(Abhi)

    0
0  20
1  21
2  22
3  23
4  24
5  25
6  26
7  27
8  28
9  29


In [58]:
data = {'Name':['Tom','Nick','Prit','Jash'],'Age':[20,12,34,23]}
df = pd.DataFrame(data)
df

Name  Age
0   Tom   20
1  Nick   12
2  Prit   34
3  Jash   23

In [61]:
index_list = ['A','B','C','D']
df = pd.DataFrame(data,index_list)
df

Name  Age
A   Tom   20
B  Nick   12
C  Prit   34
D  Jash   23