In [3]:
## 1.Write a program to find and manipulate the shape of ndarray.

import numpy as np

array=np.random.random(10)

array

array([0.10011982, 0.0035853 , 0.08286477, 0.11742325, 0.02664149,
       0.35424054, 0.6864603 , 0.26669246, 0.67557124, 0.92336145])

In [20]:
## 2.Write a program to find the logarithmic value of numbers from 31 to 40.

import math

for i in range(31,41):
    print(math.log(i))
    
print(i)

3.4339872044851463
3.4657359027997265
3.4965075614664802
3.5263605246161616
3.5553480614894135
3.58351893845611
3.6109179126442243
3.6375861597263857
3.6635616461296463
3.6888794541139363
40


In [2]:
## 3.Write a program to create a 3x2 matrix containing zeros and another matrix containing one only.

import numpy as np

dimensions = (3, 2)

a = np.zeros(dimensions)

b = np.ones(dimensions)
print(a)

print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
## 4.Write a program to convert regular array into an ndarray. 

import numpy as np

A = np.array([1,3,2,4,6])
type(A)

numpy.ndarray

In [19]:
A

array([1, 3, 2, 4, 6])

In [10]:
## 5.Write a program to create an ndarray containing characters of a string.

import numpy as np

A = np.char.array(['ABHI', 'PARTH'])
A

chararray(['ABHI', 'PARTH'], dtype='<U5')

In [30]:
## 6. Write a program to find transpose of two metrics and then perform addition on them.

import numpy as np

P = np.array([(1,2,3),(4,5,6)])
Q = np.array([(7,8,9),(2,5,7)])

print("martix 1:")
A = np.transpose(P)
print(A)

print("matrix 2:")
B = np.transpose(Q)
print(B)

print("Addition:")
E = A + B
print(E)

martix 1:
[[1 4]
 [2 5]
 [3 6]]
matrix 2:
[[7 2]
 [8 5]
 [9 7]]
Addition:
[[ 8  6]
 [10 10]
 [12 13]]


In [40]:
## 7. Write a program to explain various string manipulation methods on Numpy arrays.

import numpy as np
A = np.char.center('ABHI', 20,fillchar = '*')
print(A)

B = np.char.title('IMAGIKA')
print(B)

C = np.char.lower('SURAT')
print(C)

D = np.char.upper('ahmedabad')
print(D)

********ABHI********
Imagika
surat
AHMEDABAD


In [34]:

##8. Write a program to perform various arithmetic functions on Numpy arrays.
import numpy as np

A = np.array([(3,4,5,6),(1,4,7,9)])
print(A)

B = np.array([(2,8,4,12),(5,10,15,25)])
print(B)

C = np.add(A,B)
print(C)

D = np.subtract(A,B)
print(D)

E = np.multiply(A,B)
print(E)

F = np.divide(A,B)
print(F)

[[3 4 5 6]
 [1 4 7 9]]
[[ 2  8  4 12]
 [ 5 10 15 25]]
[[ 5 12  9 18]
 [ 6 14 22 34]]
[[  1  -4   1  -6]
 [ -4  -6  -8 -16]]
[[  6  32  20  72]
 [  5  40 105 225]]
[[1.5        0.5        1.25       0.5       ]
 [0.2        0.4        0.46666667 0.36      ]]


In [4]:
###9. Write a program to explain matrix manipulation using ndarrays.

import numpy as np

A = np.array([(3,4),(1,4)])
print(A)

B = np.array([(2,8),(5,10)])
print(B)

C = np.sqrt(A)
print(C)

D = np.dot(A,B)
print(D)


[[3 4]
 [1 4]]
[[ 2  8]
 [ 5 10]]
[[1.73205081 2.        ]
 [1.         2.        ]]
[[26 64]
 [22 48]]


In [ ]:
###10. Assume That You have this Array [ [ 5 , 10 , 15 ] , [ 20 , 12 , 28 ]] , Now At output give Only that Value which is Greater Than 12 . 

import numpy as np

