In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
irisData = load_iris()

In [4]:
X = irisData.data
Y = irisData.target

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
X_train

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

In [10]:
X_test

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751],
       [ 0.84210448,  0.30929911,  0.78699794,  1.09012776],
       [-1.23014297, -0.13788033, -1.33331205, -1.44608785],
       [-0.37686461,  0.98006827, -1.39061772, -1.31260282],
       [-1.10824606,  0.08570939, -1.27600637, -1.44608785],
       [-0.86445224,  1.65083742, -1.27600637, -1.17911778],
       [ 0.59831066,  0.53288883,  0.55777524,  0.55618763],
       [ 0.84210448, -0.

In [11]:
from sklearn.decomposition import PCA

In [12]:
pca = PCA(random_state=42)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [13]:
X_train

array([[-2.74105758e+00,  4.15797708e-01,  3.14365461e-01,
        -2.47625244e-02],
       [-2.21457679e+00,  2.60476167e+00,  3.00057396e-02,
        -5.93838587e-02],
       [ 9.26828081e-01,  5.29167275e-01, -5.16367756e-01,
        -1.15717824e-01],
       [-2.29342856e+00,  1.08078302e-01,  7.23586598e-02,
         1.30145402e-01],
       [-2.52454797e+00, -4.96938209e-01,  2.80546624e-01,
         6.33380473e-02],
       [ 1.61592869e+00, -8.45685458e-01, -4.48630063e-02,
        -2.32971927e-01],
       [ 7.85811169e-01,  6.00685859e-01, -1.04198659e-01,
        -1.60171618e-02],
       [-2.13514310e+00,  5.02812496e-01, -2.26196129e-01,
        -1.48155319e-02],
       [-2.35529452e+00,  6.11496470e-01, -1.90834084e-03,
         3.13132248e-02],
       [-2.57444158e+00,  1.72650436e+00,  3.76803984e-02,
         2.24991756e-01],
       [ 1.21265689e+00, -6.72243586e-01,  5.15068936e-01,
         2.87355252e-02],
       [ 4.87715650e-01,  8.28563454e-01,  4.45117796e-01,
      

In [14]:
X_test

array([[ 6.79465750e-01, -3.85005767e-01, -3.12739809e-01,
         2.68096915e-01],
       [-1.85948524e+00,  1.36754843e+00, -3.86920672e-01,
        -6.74350799e-02],
       [ 3.37418698e+00,  8.28335359e-02, -7.14994824e-01,
        -5.91145539e-02],
       [ 7.15433448e-01, -2.05865391e-01,  7.01263341e-02,
         2.64777284e-02],
       [ 1.30528623e+00, -3.40101766e-02, -7.45456994e-01,
        -4.89954665e-02],
       [-1.79741679e+00,  4.08899548e-01, -2.89362053e-01,
        -2.46833136e-01],
       [ 1.18877970e-02, -4.23833100e-01,  1.76846398e-01,
        -1.18912488e-01],
       [ 1.96579214e+00,  7.05357981e-01,  1.27227530e-01,
        -4.88441182e-01],
       [ 1.26604398e+00, -1.54750123e+00, -5.10706881e-01,
        -2.35314721e-01],
       [ 2.83941544e-01, -7.43311808e-01, -1.73973261e-01,
        -3.15954045e-02],
       [ 1.42644878e+00,  6.95910516e-01,  2.80077392e-01,
        -1.22716200e-01],
       [-2.19308450e+00, -7.23566150e-01, -2.60697852e-01,
      

In [15]:
# pca.components_ returns the set of all eigenvectors found for your projection

pca.components_

array([[ 0.5174275 , -0.27120139,  0.58228005,  0.56539237],
       [ 0.39110948,  0.91812675,  0.02180681,  0.06000927],
       [-0.71486989,  0.25975661,  0.14085828,  0.63375586],
       [-0.26127227,  0.12656849,  0.80039575, -0.52448438]])

In [16]:
# explained_variance_ratio_ which returns the variance caused by each of the principal components

pca.explained_variance_ratio_

array([0.72551423, 0.23000922, 0.03960774, 0.00486882])

In [17]:
pca = PCA(n_components=2)

In [18]:
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [19]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [20]:
Y_pred = classifier.predict(X_test)
Y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0])

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, Y_pred)
print(cm)

[[10  0  0]
 [ 0  7  2]
 [ 0  1 10]]
