In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
dataset = pd.read_excel("Position.xlsx")

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Position  10 non-null     object
 1   Level     10 non-null     int64 
 2   Salary    10 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


In [4]:
dataset.head()

Position  Level  Salary
0    Business analyst      1   45000
1  Junior Counsultant      2   50000
2  Senior Counsultant      3   60000
3             Manager      4   65000
4      CountryManager      5  110000

In [5]:
X = dataset.iloc[:, 1:-1].values
Y = dataset.iloc[:, -1].values

In [6]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [7]:
Y

array([ 45000,  50000,  60000,  65000, 110000, 130000, 145000, 167000,
       210000, 300000], dtype=int64)

## Training The Linear Regression Model on The Whole Dataset

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

LinearRegression()

## Training The Polynomial Regression 

In [10]:
from sklearn.preprocessing import PolynomialFeatures

In [11]:
poly_reg = PolynomialFeatures(degree = 4)

In [12]:
X_poly = poly_reg.fit_transform(X)
X_poly

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00, 1.600e+01],
       [1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01, 8.100e+01],
       [1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01, 2.560e+02],
       [1.000e+00, 5.000e+00, 2.500e+01, 1.250e+02, 6.250e+02],
       [1.000e+00, 6.000e+00, 3.600e+01, 2.160e+02, 1.296e+03],
       [1.000e+00, 7.000e+00, 4.900e+01, 3.430e+02, 2.401e+03],
       [1.000e+00, 8.000e+00, 6.400e+01, 5.120e+02, 4.096e+03],
       [1.000e+00, 9.000e+00, 8.100e+01, 7.290e+02, 6.561e+03],
       [1.000e+00, 1.000e+01, 1.000e+02, 1.000e+03, 1.000e+04]])

In [13]:
lin_reg_1 = LinearRegression()

In [14]:
lin_reg_1.fit(X_poly,Y)

LinearRegression()

In [15]:
from sklearn.metrics import r2_score, mean_squared_error

In [16]:
## linear prediction
y_pred_lin = lin_reg.predict(X)
print(y_pred_lin)

[ 13381.81818182  38896.96969697  64412.12121212  89927.27272727
 115442.42424242 140957.57575758 166472.72727273 191987.87878788
 217503.03030303 243018.18181818]


In [17]:
## linear r2 score and MSE
r2_lin = r2_score(Y,y_pred_lin)
print("r2 score of linear :",r2_lin)
mse_lin = mean_squared_error(Y,y_pred_lin)
print("MSE of linear :",mse_lin)

r2 score of linear : 0.8949835355063678
MSE of linear : 630220606.0606058


In [19]:
## poly linear prediction
y_pred_poly = lin_reg_1.predict(X_poly)
print(y_pred_poly)

[ 48653.84615392  41719.11421915  57337.41258744  81261.65501168
 104772.72727275 124679.4871795  143318.76456876 168555.36130533
 213782.05128198 297919.58041948]


In [20]:
## polynomial r2 score and MSE
r2_poly = r2_score(Y,y_pred_poly)
print("r2 score of Polynomial linear regression :",r2_poly)
mse_poly = mean_squared_error(Y,y_pred_poly)
print("MSE of Polynomial linear regression: ",mse_poly)

r2 score of Polynomial linear regression : 0.9927853206344365
MSE of Polynomial linear regression:  43296445.22144534
